### ISSUE TITLE
font.conf 会导致 Github 的代码字体 font-family 使用 Noto Sans CJK SC

### ISSUE THREAD

**Issue by Tim-Paik** [szclsya/dotfiles#1]
如题
```
  <match>
    <edit mode="prepend" name="family">
      <string>Noto Sans</string>
    </edit>
  </match>
```
这一段会导致优先使用 Noto Sans 而不是 Mono 字体

将 `prepend` 改为 `append_last` 就正常了

**Comment by szclsya** [comment]
Fixed in 3f0d0bbc72ca18508b95a2855d28ba137b1fa8af.

这件事还挺复杂... 去掉 prepend 后虽然 GitHub 显示 monospace 了，但是会用 GitHub 配置的字体优先列表，所以如果想用我们设置的字体的话还需要将几个常用的 Linux 字体名匹配一下。
以及 GitHub 使用的 sans-serif 列表里面有个 Helvetica，会被 fontconfig 替换成 Nimbus Sans，如果想用配置的字体还得把这个字体禁用掉。
（当然，如果想用 GitHub 提供的字体预设的话就不用这么麻烦了）
